# Generated by Django 4.0.2 on 2022-02-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='s_best_selling',
            field=models.BooleanField(default=False),
        ),
    ]
